import { readFileSync } from "node:fs";
const read = (file) => readFileSync(file, "utf8");
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const has = (source, pattern, message) => assert(pattern.test(source), message);
const types = read("src/lib/types.ts");
const assets = read("src/lib/library-assets.ts");
const database = read("src/lib/database.ts");
const route = read("src/app/api/library/assets/batch/route.ts");

has(types, /mode: "ids";\s*assetIds: string\[\]/, "Explicit id selection is missing.");
has(types, /mode: "query";\s*filters: LibraryAssetFilters;\s*excludedAssetIds\?: string\[\]/, "Query selection with exclusions is missing.");
has(assets, /resolveLibrarySelectionIds[\s\S]*queryLibraryAssetIdsFromDb/, "Query selection must resolve in the database.");
has(database, /queryLibraryAssetIdsFromDb[\s\S]*NOT IN/, "Server-side exclusions are missing.");
has(assets, /requireManageableCollections\(account, collectionIds\)[\s\S]*updateCollectionMemberships/, "All target collections must be validated before writes.");
has(assets, /canReadAsset\(account, asset\)[\s\S]*replaceLibraryAssetCollectionsFromDb/, "Readable shared assets must be organizable without asset ownership.");
has(assets, /unchangedAssetIds\.push/, "Idempotent collection changes must report unchanged assets.");
has(assets, /failures\.push\(\{ assetId, error:/, "Batch operations must report per-item failures.");
has(assets, /runLibraryBatch[\s\S]*offset \+= 100/, "Large server-side batches must be processed in bounded chunks.");
has(assets, /deleteLibraryCollection[\s\S]*reparented[\s\S]*deleteLibraryCollectionFromDb/, "Collection deletion must promote children before deletion.");
has(database, /ON DELETE CASCADE[\s\S]*library_collection_assets/, "Collection relation cleanup is missing.");
has(route, /action === "set_favorite"/, "Batch favorites are missing.");
has(route, /action === "set_visibility"/, "Batch visibility is missing.");
has(route, /confirm !== true/, "Permanent batch deletion must require confirmation.");
has(route, /parseLibrarySelection/, "Batch route must parse server-side selections.");
console.log("Unified library collection and query-selection batch contracts ok");
