import assert from "node:assert/strict";
import { mkdirSync, writeFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import sharp from "sharp";
import type { GeneratedPost } from "../../src/lib/types";

async function main() {
  assert.ok(process.env.REVIEW_TEST_ROOT);
  process.chdir(process.env.REVIEW_TEST_ROOT);
  const db = await import("../../src/lib/database");
  const store = await import("../../src/lib/generated-posts");
  const query = await import("../../src/lib/review-posts");
  const { markSourceRewritten } = await import("../../src/lib/content-pool");
  const { changedReviewFields } = await import("../../src/lib/review-contract");
  const { getReviewThumbnail } = await import("../../src/lib/review-thumbnails");
  await db.readGeneratedPostsFromDb();
  const seed = new DatabaseSync(db.sqliteStorePath);
  const actor = { id: "alice", displayName: "Alice", role: "operator" as const };
  const other = { ...actor, id: "bob" };
  const admin = { ...actor, role: "admin" as const };
  const now = "2026-09-14T10:00:00.000Z";
  const makePost = (i: number): GeneratedPost => ({ id: `p-${String(i).padStart(4,"0")}`, sourceItemId: "source-0", ownerUserId: actor.id, ownerDisplayName: "Alice", title: `Post ${i}`, body: "Long body ".repeat(60), imagePrompt: "prompt", imageUrls: ["/generated/a.png"], videoUrls: ["/media/video.mp4"], materialPaths: [], aiNotes: [], status: i % 2 ? "draft" : "approved", platform: "xiaohongshu", updatedAt: now, createdAt: now, sourceBatchId: "batch" });
  for (let i=0;i<125;i++) await db.saveGeneratedPostToDb(makePost(i));
  await db.saveGeneratedPostToDb({ ...makePost(200), ownerUserId: other.id, ownerDisplayName: "Bob" });
  const first = await query.listReviewPosts(actor, new URLSearchParams());
  assert.equal(first.posts.length, 50);
  assert.ok(first.nextCursor);
  assert.equal(first.posts[0].id,"p-0124");
  assert.equal(first.posts[0].mediaCount,2);
  assert.equal(first.posts[0].excerpt.length,160);
  assert.ok(!("body" in first.posts[0]) && !("imageUrls" in first.posts[0]));
  const second = await query.listReviewPosts(actor, new URLSearchParams({ cursor: first.nextCursor! }));
  const third = await query.listReviewPosts(actor, new URLSearchParams({ cursor: second.nextCursor! }));
  assert.equal(new Set([...first.posts,...second.posts,...third.posts].map(row=>row.id)).size,125);
  assert.equal(third.nextCursor,undefined);
  assert.equal((await query.getReviewMetadata(actor,new URLSearchParams())).summary.total,125);
  assert.equal((await query.getReviewMetadata(admin,new URLSearchParams())).summary.total,126);
  for (const filters of [{q:"Post 124"}, {q:"long BODY", status:"approved"}, {author:"Alice", platform:"xiaohongshu", sourceBatchId:"batch"}]) assert.ok((await query.listReviewPosts(actor,new URLSearchParams(filters))).posts.length);
  for (const filters of [{q:"%"}, {author:"Bob"}, {sourceBatchId:"missing"}, {since:"2026-09-15T00:00:00Z"}, {until:now}]) assert.equal((await query.listReviewPosts(actor,new URLSearchParams(filters))).posts.length,0);
  await assert.rejects(query.listReviewPosts(actor,new URLSearchParams({cursor:"bad"})), /cursor/);
  assert.equal(await store.getGeneratedPost("p-0200",actor),undefined);
  assert.deepEqual((await store.getGeneratedPostsByIds(["p-0002","missing","p-0001","p-0200"],actor)).map(p=>p.id),["p-0002","p-0001"]);
  const original=makePost(1);
  assert.deepEqual(changedReviewFields({...original,body:"Edit"},original),{body:"Edit"});
  assert.deepEqual(changedReviewFields({...original,videoUrls:[]},original),{videoUrls:[]});
  assert.deepEqual(changedReviewFields({...original,feishuVehicle:"Vehicle"},original),{feishuVehicle:"Vehicle"});
  // Malformed unrelated JSON must not be decoded by a single-record save.
  seed.prepare("UPDATE generated_posts SET data_json='{}' WHERE id='p-0003'").run();
  await store.saveGeneratedPost({...original,title:"Edited"},actor);
  assert.equal((await store.getGeneratedPost(original.id,actor))?.title,"Edited");
  const project = (id: string, ids: string[]) => ({id,normalizedQuery:id,query:id,createdAt:now,updatedAt:now,items:ids.map(id=>({id,ownerUserId:actor.id,platform:"xiaohongshu",title:"Source",images:[],metrics:{},poolStatus:"new",usedCount:0,analysis:{hook:"fixture"}}))});
  const insert=seed.prepare("INSERT INTO content_projects VALUES (?,?,?,?,?,?,?)");
  for(const value of [project("a",["source-0","source-1"]),project("b",["other"])]) insert.run(value.id,value.id,value.id,now,now,null,JSON.stringify(value));
  seed.exec("CREATE TABLE touched(id TEXT); CREATE TRIGGER source_update AFTER UPDATE ON content_projects BEGIN INSERT INTO touched VALUES (new.id); END;");
  await Promise.all([markSourceRewritten("source-0",{...original,status:"approved"},actor),markSourceRewritten("source-1",{...original,status:"approved"},actor)]);
  await markSourceRewritten("source-0",{...original,status:"draft"},actor);
  await markSourceRewritten("source-0",{...original,status:"published"},other);
  const saved=JSON.parse((seed.prepare("SELECT data_json FROM content_projects WHERE id='a'").get() as {data_json:string}).data_json);
  assert.deepEqual(saved.items.map((item:{poolStatus:string;usedCount:number})=>[item.poolStatus,item.usedCount]),[["approved",1],["approved",1]]);
  assert.equal(saved.approvedItems,2);
  assert.ok(seed.prepare("SELECT id FROM touched").all().every(row=>row.id==="a"));
  assert.equal(seed.prepare("SELECT id FROM touched").all().length,2);
  mkdirSync("public/generated",{recursive:true});
  writeFileSync("public/generated/a.png",await sharp({create:{width:400,height:200,channels:3,background:"red"}}).png().toBuffer());
  const thumb=await getReviewThumbnail("/generated/a.png",240);
  assert.equal((await sharp(thumb.bytes).metadata()).width,240);
  assert.equal((await getReviewThumbnail("/generated/a.png",240)).etag,thumb.etag);
  assert.equal((await sharp((await getReviewThumbnail("/generated/a.png",960)).bytes).metadata()).height,960);
  const remoteBytes=await sharp({create:{width:300,height:400,channels:3,background:"green"}}).png().toBuffer();
  let remoteCalls=0;
  const realFetch=globalThis.fetch;
  globalThis.fetch=async (_input, init) => {
    assert.equal(init?.redirect,"error");
    remoteCalls++;
    return new Response(new Uint8Array(remoteBytes),{headers:{"content-type":"image/png"}});
  };
  try {
    const [one,two]=await Promise.all([getReviewThumbnail("https://fixture.invalid/image.png",240),getReviewThumbnail("https://fixture.invalid/image.png",240)]);
    assert.equal(remoteCalls,1);
    assert.equal(one.etag,two.etag);
    await getReviewThumbnail("https://fixture.invalid/image.png",240);
    assert.equal(remoteCalls,1);
    globalThis.fetch=async()=>new Response("failure",{status:502});
    await assert.rejects(getReviewThumbnail("https://fixture.invalid/failure.png",240),/502/);
  } finally { globalThis.fetch=realFetch; }
  writeFileSync("public/generated/bad.png","invalid");
  await assert.rejects(getReviewThumbnail("/generated/bad.png",240));
  await assert.rejects(getReviewThumbnail("/generated/../../data/fluxpost.db",240));
  assert.notEqual(query.reviewImageVersion("a"),query.reviewImageVersion("b"));
  seed.close();
  console.log("Review pagination, ownership, patch, targeted source concurrency and thumbnail checks passed.");
}
main().catch(error=>{ console.error(error);process.exitCode=1; });
