import { readFileSync } from 'node:fs';
import path from 'node:path';
const r=(p)=>readFileSync(path.join(process.cwd(),p),'utf8');
const has=(s,p,m)=>{if(!p.test(s))throw new Error(m)};
const types=r('src/lib/types.ts'), route=r('src/app/api/simple/runs/route.ts'), simple=r('src/lib/simple-runs.ts'), page=r('src/app/page.tsx'), viral=r('src/lib/viral-replication.ts'), config=r('src/lib/config.ts'), imageGeneration=r('src/lib/image-generation.ts'), libraryAssets=r('src/lib/library-assets.ts');
has(types,/viralUrl\?:\s*string/,'viralUrl missing');
has(types,/viralImitateImages\?:\s*boolean/,'viralImitateImages missing');
has(types,/viralMaterialPaths\?:\s*string\[\]/,'viralMaterialPaths missing from SimpleRunInput');
has(types,/viralResult\?:\s*SimpleRunViralResult/,'viralResult missing');
has(types,/referenceUrls\?:\s*string\[\]/,'SourceImageTask referenceUrls missing');
has(types,/pairedImageCount\?:\s*number/,'pairedImageCount missing');
has(types,/MaterialVisualProfile/,'material profile missing');
has(config,/VIRAL_IMAGE_IMITATION_PROMPT/,'viral image imitation env var missing');
has(config,/viralImageImitationPrompt/,'viral image imitation app config missing');
has(route,/body\.sourceMode === "original" \? "original" : body\.sourceMode === "viral" \? "viral"/,'route viral mode missing');
has(route,/viralUrl:\s*body\.viralUrl/,'route viralUrl missing');
has(route,/viralImitateImages:\s*body\.viralImitateImages === true/,'route viralImitateImages default-off mapping missing');
has(route,/viralMaterialAssetIds\?:\s*string\[\]/,'route request body should accept viral vehicle asset ids');
has(route,/materialAssetIds\?:\s*string\[\]/,'route request body should accept general vehicle asset ids');
has(route,/resolveLibraryAssetSelections\([\s\S]*body\.materialAssetIds[\s\S]*"vehicle"/,'route should validate general material ids against the vehicle library');
has(route,/resolveLibraryAssetSelections\([\s\S]*body\.viralMaterialAssetIds[\s\S]*"vehicle"/,'route should validate viral material ids against the vehicle library');
has(route,/viralMaterialPaths:\s*viralMaterialAssets\.map\(\(asset\) => asset\.publicUrl\)/,'route should freeze validated viral vehicle URLs into the durable run input');
has(route,/materialPaths:\s*materialAssets\.map\(\(asset\) => asset\.publicUrl\)/,'route should freeze validated general vehicle URLs into the durable run input');
has(libraryAssets,/resolveLibraryAssetSelections[\s\S]*canReadAsset\(account, asset\)[\s\S]*asset\.roles\.includes\(role\)/,'vehicle selection resolution must enforce read access and role membership');
has(simple,/isSimpleRunViralMode\(normalizedInput\)[\s\S]*runSimpleViralWorkflow/,'worker viral branch missing');
has(simple,/sourceMode === "viral" && !viralUrl/,'viral validation missing');
has(simple,/const generateImages = shouldGenerateImages\(normalizedInput\)[\s\S]*const imitateImages = generateImages && normalizedInput\.viralImitateImages === true/,'viral image imitation must be explicit opt-in and respect the image-generation switch');
has(simple,/viralMaterialPaths:\s*sourceMode === "viral" \? normalizeMaterialPaths\(input\.viralMaterialPaths\) : undefined/,'viralMaterialPaths normalization missing');
has(simple,/if \(sourceMode === "viral" && input\.generateImages !== false && input\.viralImitateImages === true && !normalizeMaterialPaths\(input\.viralMaterialPaths\)\.length\)/,'viral image imitation should require explicit selected vehicle images only when image generation is enabled');
has(simple,/const viralMaterialPaths = normalizedInput\.viralMaterialPaths \|\| \[\]/,'viral workflow should use selected vehicle material paths');
has(simple,/if \(imitateImages\)[\s\S]*analyzeViralImages\(source\.images\)[\s\S]*pairViralImagesWithMaterials\(source\.images, viralMaterialPaths, normalizedInput\.keyword, imageAnalysis\.specs\)/,'viral image imitation must analyze source image styles and pair source images with selected vehicle images in order');
has(simple,/Viral image imitation is disabled; generating copy only/,'viral text-only path missing');
has(simple,/Only text was generated; image generation is disabled for this viral run/,'viral disabled image-generation path should still produce text');
has(simple,/viralImitateImages:\s*sourceMode === "viral" \? input\.viralImitateImages === true : undefined/,'viralImitateImages normalization missing');
has(simple,/enqueueFeishuPublishJob\(persistedApprovedPosts/,'Normalized persisted posts must reuse the Feishu queue');
for(const n of ['analyzeViralSource','analyzeViralImages','indexMaterialImages','pairViralImagesWithMaterials','buildViralGeneratedPost'])has(viral,new RegExp('export (async )?function '+n),n+' missing');
has(viral,/imitateImages\?:\s*boolean/,'viral generated post image imitation option missing');
has(viral,/input\.imitateImages === false \? undefined : imageTasks/,'text-only viral generation must not pass image tasks');
has(viral,/referenceUrls:\s*\[pair\.sourceImageUrl\]/,'viral image task must attach source image as second reference');
has(viral,/appConfig\.viralImageImitationPrompt/,'viral image prompt must use app config');
has(viral,/provider:\s*input\.useComfyUiKlein === true \? "comfyui_klein" : "openai_images"/,'viral image tasks must respect the simple-run ComfyUI routing policy');
has(simple,/buildViralGeneratedPost\(\{[\s\S]*useComfyUiKlein:\s*normalizedInput\.useComfyUiKlein === true && isComfyUiKleinConfigured\(\)/,'viral workflow must respect the user ComfyUI switch and configured availability');
has(viral,/function buildViralImagePrompt[\s\S]*appConfig\.viralImageImitationPrompt[\s\S]*Target vehicle\/product keyword/,'viral image prompt should use the configured viral imitation prompt as the lead instruction');
if (/function buildViralImagePrompt[\s\S]*resolveViralImageStrategyPrompt/.test(viral)) throw new Error('viral image prompt should not append the generic car-exterior strategy prompt after the configured viral prompt');
has(imageGeneration,/function getTaskReferenceImages/,'image generation must collect task reference images');
has(imageGeneration,/task\.referenceUrls/,'image generation must pass additional task reference images');
has(imageGeneration,/task\.provider === "comfyui_klein" && isComfyUiKleinConfigured\(\)[\s\S]*return runComfyUiKleinImageTask/, 'strict viral tasks should be allowed to use configured ComfyUI before the OpenAI Images endpoint guard');
has(page,/simpleViralUrl/,'UI viral URL missing');
has(page,/simpleViralImitateImages/,'UI viral image imitation switch state missing');
has(page,/simpleViralMaterialAssetIds/,'UI selected viral material asset-id state missing');
has(page,/async function loadVehicleLibrary\(\)[\s\S]*do \{[\s\S]*role: "vehicle"[\s\S]*nextCursor[\s\S]*\} while \(cursor\)/,'UI must page through the complete authenticated vehicle library');
has(page,/viralMaterialCandidates/,'UI viral material candidates missing');
has(page,/viralMaterialFolders/,'UI viral material folder candidates missing');
has(page,/simpleViralMaterialFolderId/,'UI should track the active viral material folder independently from selected image paths.');
has(page,/displayedViralMaterialCandidates/,'UI should render viral material candidates filtered by the active vehicle folder.');
has(page,/findMatchingViralMaterialFolderId\(viralMaterialFolders,\s*simpleKeyword\)/,'UI should infer the active viral material folder from the simple keyword.');
has(page,/onToggleViralMaterialAsset/,'UI viral material selection handler missing');
has(page,/onToggleViralMaterialFolder/,'UI viral material folder selection handler missing');
has(page,/const availableSlots = Math\.max\(0, maxSimpleImageTasksPerPost - withoutFolder\.length\)[\s\S]*folder\.assetIds\.slice\(0, availableSlots\)/,'Vehicle collection selection must respect the global image limit');
has(page,/onPreviewViralMaterial/,'UI viral material preview handler missing');
has(page,/buildViralMaterialFolders\(vehicleLibrary\.collections, vehicleLibrary\.assets, simpleViralMaterialAssetIds\)/,'UI should build selectable viral material groups from vehicle-library collections.');
has(page,/buildViralMaterialCandidates\(vehicleLibrary\.assets, vehicleLibrary\.collections\)/,'UI viral material candidates should come from the TOS-backed vehicle library.');
has(page,/onToggleFolder\(folder\.id\)/,'UI viral folder buttons should toggle folder selection.');
has(page,/viralMaterialCandidates=\{displayedViralMaterialCandidates\}/,'Simple workspace should receive the folder-filtered viral image list.');
has(page,/activeFolderId === folder\.id/,'UI viral folder buttons should mark the folder driving the visible image list.');
has(page,/asset\.collectionIds\.includes\(activeSimpleViralMaterialFolderId\)/,'Visible viral image list should be filtered by active vehicle collection.');
has(page,/folder\.selectedCount[\s\S]*\/[\s\S]*folder\.imageCount/,'UI viral folder cards should show selected image count for each folder.');
has(page,/type PreviewState[\s\S]*selectedImageUrls:\s*string\[\]/,'Preview dialog should carry selected image state.');
has(page,/onToggle=\{\(url\) => \{ const asset = vehicleLibrary\.assets\.find[\s\S]*onToggleViralMaterialAsset\(asset\.id\)/,'Preview selection should resolve the URL back to the selected vehicle asset id.');
has(page,/selectedImageUrls = vehicleLibrary\.assets\.filter[\s\S]*asset\.publicUrl/,'Viral material previews should derive selected URLs from vehicle asset ids.');
has(page,/\.slice\(0, maxSimpleImageTasksPerPost\)/,'Preview selection should enforce the vehicle image selection limit.');
has(page,/preview\.selectedImageUrls\.includes\(path\)/,'Preview dialog should derive the current image selection state from the active preview image.');
has(page,/onClick=\{\(\) => onPreview\(asset\.id\)\}/,'UI viral material preview should use the vehicle asset id.');
has(page,/<Maximize2 className="h-3\.5 w-3\.5" \/>/,'UI viral material preview button should use preview icon');
if (/\/api\/materials\//.test(page)) throw new Error('Home must not reference retired local-material APIs');
has(page,/请选择至少 1 张车型图用于图片模仿/,'UI viral image selection validation copy missing');
has(page,/viralUrl:\s*sourceMode === "viral" \? viralUrl : undefined/,'UI viral payload missing');
has(page,/viralImitateImages:\s*sourceMode === "viral" \? simpleViralImitateImages : undefined/,'UI viral image imitation payload missing');
has(page,/viralMaterialAssetIds:\s*sourceMode === "viral" && simpleGenerateImages && simpleViralImitateImages \? simpleViralMaterialAssetIds : undefined/,'UI should submit selected viral vehicle ids only when image imitation is enabled');
has(page,/materialAssetIds:\s*vehicleMaterialAssetIds/,'UI should submit accessible vehicle ids for general material references');
console.log('Simple viral run check passed.');
