import { readFileSync } from "node:fs";
const read = (file) => readFileSync(file, "utf8");
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const has = (source, pattern, message) => assert(pattern.test(source), message);
const assets = read("src/lib/library-assets.ts");
const tagging = read("src/lib/library-tagging.ts");
const importRoute = read("src/app/api/library/import/route.ts");
const tagsRoute = read("src/app/api/library/tags/route.ts");
const home = read("src/app/page.tsx");
const canvas = read("src/lib/canvas/scheduler.ts");

has(assets, /collectionIds\?: string\[\]/, "Imports must accept optional collections.");
has(assets, /collectionIds,[\s\S]*taggingStatus: "idle"/, "Unified imports must persist collection relationships without automatic tagging.");
has(importRoute, /form\.has\("role"\)[\s\S]*no longer supported/, "Import API must reject legacy roles.");
assert(!/kickLibraryTaggingWorker/.test(importRoute), "Imports must not wake the tagging worker.");
has(tagging, /enqueueLibraryTagging[\s\S]*mode === "failed"/, "Manual retry and full retag modes are missing.");
assert(!/asset\.roles|current\.roles|eligible\.roles/.test(tagging), "Tagging still depends on a library role.");
has(tagsRoute, /parseLibrarySelection/, "Batch tags must accept server-side selection snapshots.");
has(home, /name === "车型库"[\s\S]*collectionId/, "Simple mode must default to the migrated vehicle root collection.");
assert(!/href="\/library\?role=/.test(home), "Home still links to role-specific libraries.");
assert(!/role:\s*"reference"|role:\s*"vehicle"|source\.role/.test(canvas), "Canvas scheduler still persists library roles.");
has(canvas, /source\.mode === "library-filter"[\s\S]*resolveScheduleAssetPool\(account, source\.filter\)/, "Canvas must resolve unified filters before freezing snapshots.");
console.log("Manual tagging, migrated simple-mode root, and unified Canvas consumer contracts ok");
