import { readFileSync } from 'node:fs';
import path from 'node:path';
const r=(p)=>readFileSync(path.join(process.cwd(),p),'utf8');
const has=(s,p,m)=>{if(!p.test(s))throw new Error(m)};
const types=r('src/lib/types.ts'), route=r('src/app/api/simple/runs/route.ts'), simple=r('src/lib/simple-runs.ts'), page=r('src/app/page.tsx'), check=r('scripts/harness/check.ps1'), viral=r('src/lib/viral-replication.ts'), config=r('src/lib/config.ts'), imageGeneration=r('src/lib/image-generation.ts'), materialPreview=r('src/app/api/materials/preview/route.ts');
has(types,/viralUrl\?:\s*string/,'viralUrl missing');
has(types,/viralImitateImages\?:\s*boolean/,'viralImitateImages missing');
has(types,/viralMaterialPaths\?:\s*string\[\]/,'viralMaterialPaths missing from SimpleRunInput');
has(types,/viralResult\?:\s*SimpleRunViralResult/,'viralResult missing');
has(types,/referenceUrls\?:\s*string\[\]/,'SourceImageTask referenceUrls missing');
has(types,/pairedImageCount\?:\s*number/,'pairedImageCount missing');
has(types,/MaterialVisualProfile/,'material profile missing');
has(config,/VIRAL_IMAGE_IMITATION_PROMPT/,'viral image imitation env var missing');
has(config,/viralImageImitationPrompt/,'viral image imitation app config missing');
has(route,/body\.sourceMode === "original" \? "original" : body\.sourceMode === "viral" \? "viral"/,'route viral mode missing');
has(route,/viralUrl:\s*body\.viralUrl/,'route viralUrl missing');
has(route,/viralImitateImages:\s*body\.viralImitateImages === true/,'route viralImitateImages default-off mapping missing');
has(route,/viralMaterialPaths\?:\s*string\[\]/,'route request body should accept viralMaterialPaths');
has(route,/viralMaterialPaths:\s*Array\.isArray\(body\.viralMaterialPaths\)\s*\?\s*body\.viralMaterialPaths\s*:\s*\[\]/,'route should pass viralMaterialPaths through to startSimpleRun');
has(simple,/isSimpleRunViralMode\(normalizedInput\)[\s\S]*runSimpleViralWorkflow/,'worker viral branch missing');
has(simple,/sourceMode === "viral" && !viralUrl/,'viral validation missing');
has(simple,/const imitateImages = normalizedInput\.viralImitateImages === true/,'viral image imitation must be explicit opt-in');
has(simple,/viralMaterialPaths:\s*sourceMode === "viral" \? normalizeMaterialPaths\(input\.viralMaterialPaths\) : undefined/,'viralMaterialPaths normalization missing');
has(simple,/if \(sourceMode === "viral" && input\.viralImitateImages === true && !normalizeMaterialPaths\(input\.viralMaterialPaths\)\.length\)/,'viral image imitation should require explicit selected vehicle images');
has(simple,/const viralMaterialPaths = normalizedInput\.viralMaterialPaths \|\| \[\]/,'viral workflow should use selected vehicle material paths');
has(simple,/if \(imitateImages\)[\s\S]*analyzeViralImages\(source\.images\)[\s\S]*pairViralImagesWithMaterials\(source\.images, viralMaterialPaths, normalizedInput\.keyword, imageAnalysis\.specs\)/,'viral image imitation must analyze source image styles and pair source images with selected vehicle images in order');
has(simple,/Viral image imitation is disabled; generating copy only/,'viral text-only path missing');
has(simple,/viralImitateImages:\s*sourceMode === "viral" \? input\.viralImitateImages === true : undefined/,'viralImitateImages normalization missing');
has(simple,/enqueueFeishuPublishJob\(approvedPosts/,'Feishu queue reuse missing');
for(const n of ['analyzeViralSource','analyzeViralImages','indexMaterialImages','pairViralImagesWithMaterials','buildViralGeneratedPost'])has(viral,new RegExp('export (async )?function '+n),n+' missing');
has(viral,/imitateImages\?:\s*boolean/,'viral generated post image imitation option missing');
has(viral,/input\.imitateImages === false \? undefined : imageTasks/,'text-only viral generation must not pass image tasks');
has(viral,/referenceUrls:\s*\[pair\.sourceImageUrl\]/,'viral image task must attach source image as second reference');
has(viral,/appConfig\.viralImageImitationPrompt/,'viral image prompt must use app config');
has(imageGeneration,/function getTaskReferenceImages/,'image generation must collect task reference images');
has(imageGeneration,/task\.referenceUrls/,'image generation must pass additional task reference images');
has(page,/simpleViralUrl/,'UI viral URL missing');
has(page,/simpleViralImitateImages/,'UI viral image imitation switch state missing');
has(page,/simpleViralMaterialPaths/,'UI selected viral material path state missing');
has(page,/viralMaterialCandidates/,'UI viral material candidates missing');
has(page,/viralMaterialFolders/,'UI viral material folder candidates missing');
has(page,/simpleViralMaterialFolderId/,'UI should track the active viral material folder independently from selected image paths.');
has(page,/displayedViralMaterialCandidates/,'UI should render viral material candidates filtered by the active vehicle folder.');
has(page,/findMatchingViralMaterialFolderId\(viralMaterialFolders,\s*simpleKeyword\)/,'UI should infer the active viral material folder from the simple keyword.');
has(page,/onToggleViralMaterialPath/,'UI viral material selection handler missing');
has(page,/onToggleViralMaterialFolder/,'UI viral material folder selection handler missing');
has(page,/onPreviewViralMaterial/,'UI viral material preview handler missing');
has(page,/buildViralMaterialFolders\(materialLibrary\.folders, materialLibrary\.assets, simpleViralMaterialPaths\)/,'UI should build selectable viral material folders from the material library.');
has(page,/libraryAssets\.forEach\([\s\S]*?sourceLabel:\s*folderNames\.get\(asset\.folderId\)[\s\S]*?materials\.forEach\(/,'UI viral material candidates should prefer material-library assets over duplicate scanned paths so folder selections match the visible list.');
has(page,/onToggleViralMaterialFolder\(folder\.id\)/,'UI viral folder buttons should toggle folder selection.');
has(page,/viralMaterialCandidates=\{displayedViralMaterialCandidates\}/,'Simple workspace should receive the folder-filtered viral image list.');
has(page,/const active = folder\.id === activeViralMaterialFolderId/,'UI viral folder buttons should mark the folder driving the visible image list.');
has(page,/asset\.folderId === activeSimpleViralMaterialFolderId/,'Visible viral image list should be filtered by active material-library folder.');
has(page,/folder\.selectedCount[\s\S]*\/[\s\S]*folder\.imageCount/,'UI viral folder cards should show selected image count for each folder.');
has(page,/onClick=\{\(event\) => \{\s*event\.stopPropagation\(\);[\s\S]*onPreviewViralMaterial\(asset\.path\)/,'UI viral material preview should not toggle selection');
has(page,/<Maximize2 className="h-3\.5 w-3\.5" \/>/,'UI viral material preview button should use preview icon');
has(page,/\/api\/materials\/preview\?path=\$\{encodeURIComponent\(url\)\}/,'UI local material preview should route absolute paths through the material preview API');
has(materialPreview,/requireWorkspaceAccount\(request\)/,'material preview route should require workspace account');
has(materialPreview,/path\.isAbsolute\(targetPath\)/,'material preview route should only serve absolute local material paths');
has(materialPreview,/sniffBrowserSupportedImageMime/,'material preview route should verify browser-readable image content');
has(page,/请选择至少 1 张车型图用于图片模仿/,'UI viral image selection validation copy missing');
has(page,/viralUrl:\s*sourceMode === "viral" \? viralUrl : undefined/,'UI viral payload missing');
has(page,/viralImitateImages:\s*sourceMode === "viral" \? simpleViralImitateImages : undefined/,'UI viral image imitation payload missing');
has(page,/viralMaterialPaths:\s*sourceMode === "viral" && simpleViralImitateImages \? selectedSimpleViralMaterialPaths : undefined/,'UI selected viral material payload missing');
has(check,/Simple viral run check/,'baseline viral check missing');
console.log('Simple viral run check passed.');
